### ISSUE TITLE
Missing run_exports?

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/xsimd-feedstock#92]
### Comment:

Hiya,

As this is a C++ library, should the feedstock have run_exports? I've run into issues where xtensor and xsimd versions are incompatible (both installed from conda-forge).

**Comment by JohanMabille** [comment]
These are pure headers libraries, therefore run export does not really make sense.

`xsimd` is an optional dependency of `xtensor`; to guarantee compatibility between the packages, conda-forge provides the [run_constrained feature](https://conda-forge.org/docs/maintainer/adding_pkgs.html#constraining-packages-at-runtime), which we use in the feedstock of xtensor.

The issue you experienced is probably due to a wrong version pinning in the run_constrained, or even the lack or run_constraints in older versions of the xtensor feedstock.

**Comment by Tobias-Fischer** [comment]
Ok, thanks, all good then!
